apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplybyte-backend
  labels:
    app: simplybyte-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplybyte-backend
  template:
    metadata:
      labels:
        app: simplybyte-backend
    spec:
      containers:
        - name: backend
          image: simplybyte/simplybyte-backend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://simplybyte-mysql-0.mysql:3306/simplybyte"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
