apiVersion: v1
kind: Service
metadata:
  name: simplybyte-backend
spec:
  type: NodePort
  selector:
    app: simplybyte-backend
  ports:
    - port: 8090          
      targetPort: 8090    
      nodePort: 30080    
      protocol: TCP
